language: php

dist: precise

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - DB=MYSQL

before_script:
# Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer dependencies
  - composer validate
  - composer require silverstripe/installer:^4.0 --no-update
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit tests/
