language: php

dist: precise

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - DB=MYSQL

before_script:

# Init PHP
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

# Install composer dependencies
  - composer validate
  - composer install --prefer-dist
  - composer require symfony/config:^3.2 silverstripe/framework:4.0.x-dev silverstripe/config:1.0.x-dev silverstripe/admin:1.0.x-dev silverstripe/assets:1.0.x-dev silverstripe/versioned:1.0.x-dev silverstripe/cms:4.0.x-dev silverstripe/campaign-admin:1.0.x-dev silverstripe/siteconfig:4.0.x-dev silverstripe/reports:4.0.x-dev silverstripe/graphql:dev-master --no-update --prefer-dist
  - composer update

# Bootstrap cms / mysite folder
  - php ./cms/tests/bootstrap/mysite.php

script:
  - vendor/bin/phpunit tests flush=1
